/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as QISFundContractJson } from "../QISFund.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

// Custom types for the contract
export namespace QISFundTypes {
  export type Fields = {
    fundName: HexString;
    symbol: HexString;
    currentNav: bigint;
    totalSupply: bigint;
    admin: Address;
  };

  export type State = ContractState<Fields>;

  export type SharesMintedEvent = ContractEvent<{
    to: Address;
    amount: bigint;
    price: bigint;
  }>;
  export type SharesBurnedEvent = ContractEvent<{
    from: Address;
    amount: bigint;
    navAtRedemption: bigint;
  }>;
  export type NavUpdatedEvent = ContractEvent<{
    oldNav: bigint;
    newNav: bigint;
  }>;

  export interface CallMethodTable {
    getMetadata: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<[HexString, HexString]>;
    };
    getNav: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    updateNav: {
      params: CallContractParams<{ newNav: bigint }>;
      result: CallContractResult<null>;
    };
    buyShares: {
      params: CallContractParams<{ investor: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
    sellShares: {
      params: CallContractParams<{ investor: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getMetadata: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getNav: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTotalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    updateNav: {
      params: SignExecuteContractMethodParams<{ newNav: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    buyShares: {
      params: SignExecuteContractMethodParams<{
        investor: Address;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    sellShares: {
      params: SignExecuteContractMethodParams<{
        investor: Address;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<QISFundInstance, QISFundTypes.Fields> {
  encodeFields(fields: QISFundTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = { SharesMinted: 0, SharesBurned: 1, NavUpdated: 2 };
  consts = {
    ErrorCodes: {
      AdminOnly: BigInt("0"),
      ZeroAmount: BigInt("1"),
      InsufficientSupply: BigInt("2"),
      InvalidNav: BigInt("3"),
      Unauthorized: BigInt("4"),
    },
  };

  at(address: string): QISFundInstance {
    return new QISFundInstance(address);
  }

  tests = {
    getMetadata: async (
      params: Omit<
        TestContractParamsWithoutMaps<QISFundTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<[HexString, HexString]>> => {
      return testMethod(this, "getMetadata", params, getContractByCodeHash);
    },
    getNav: async (
      params: Omit<
        TestContractParamsWithoutMaps<QISFundTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getNav", params, getContractByCodeHash);
    },
    getTotalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<QISFundTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getTotalSupply", params, getContractByCodeHash);
    },
    updateNav: async (
      params: TestContractParamsWithoutMaps<
        QISFundTypes.Fields,
        { newNav: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "updateNav", params, getContractByCodeHash);
    },
    buyShares: async (
      params: TestContractParamsWithoutMaps<
        QISFundTypes.Fields,
        { investor: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "buyShares", params, getContractByCodeHash);
    },
    sellShares: async (
      params: TestContractParamsWithoutMaps<
        QISFundTypes.Fields,
        { investor: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "sellShares", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: QISFundTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const QISFund = new Factory(
  Contract.fromJson(
    QISFundContractJson,
    "",
    "00ca3d9dc515ab571dffef7206cc2ecca1c6e46ffb079f034be7b0707dd089ce",
    []
  )
);
registerContract(QISFund);

// Use this class to interact with the blockchain
export class QISFundInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<QISFundTypes.State> {
    return fetchContractState(QISFund, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeSharesMintedEvent(
    options: EventSubscribeOptions<QISFundTypes.SharesMintedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      QISFund.contract,
      this,
      options,
      "SharesMinted",
      fromCount
    );
  }

  subscribeSharesBurnedEvent(
    options: EventSubscribeOptions<QISFundTypes.SharesBurnedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      QISFund.contract,
      this,
      options,
      "SharesBurned",
      fromCount
    );
  }

  subscribeNavUpdatedEvent(
    options: EventSubscribeOptions<QISFundTypes.NavUpdatedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      QISFund.contract,
      this,
      options,
      "NavUpdated",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | QISFundTypes.SharesMintedEvent
      | QISFundTypes.SharesBurnedEvent
      | QISFundTypes.NavUpdatedEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(QISFund.contract, this, options, fromCount);
  }

  view = {
    getMetadata: async (
      params?: QISFundTypes.CallMethodParams<"getMetadata">
    ): Promise<QISFundTypes.CallMethodResult<"getMetadata">> => {
      return callMethod(
        QISFund,
        this,
        "getMetadata",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getNav: async (
      params?: QISFundTypes.CallMethodParams<"getNav">
    ): Promise<QISFundTypes.CallMethodResult<"getNav">> => {
      return callMethod(
        QISFund,
        this,
        "getNav",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: QISFundTypes.CallMethodParams<"getTotalSupply">
    ): Promise<QISFundTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        QISFund,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    updateNav: async (
      params: QISFundTypes.CallMethodParams<"updateNav">
    ): Promise<QISFundTypes.CallMethodResult<"updateNav">> => {
      return callMethod(
        QISFund,
        this,
        "updateNav",
        params,
        getContractByCodeHash
      );
    },
    buyShares: async (
      params: QISFundTypes.CallMethodParams<"buyShares">
    ): Promise<QISFundTypes.CallMethodResult<"buyShares">> => {
      return callMethod(
        QISFund,
        this,
        "buyShares",
        params,
        getContractByCodeHash
      );
    },
    sellShares: async (
      params: QISFundTypes.CallMethodParams<"sellShares">
    ): Promise<QISFundTypes.CallMethodResult<"sellShares">> => {
      return callMethod(
        QISFund,
        this,
        "sellShares",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getMetadata: async (
      params: QISFundTypes.SignExecuteMethodParams<"getMetadata">
    ): Promise<QISFundTypes.SignExecuteMethodResult<"getMetadata">> => {
      return signExecuteMethod(QISFund, this, "getMetadata", params);
    },
    getNav: async (
      params: QISFundTypes.SignExecuteMethodParams<"getNav">
    ): Promise<QISFundTypes.SignExecuteMethodResult<"getNav">> => {
      return signExecuteMethod(QISFund, this, "getNav", params);
    },
    getTotalSupply: async (
      params: QISFundTypes.SignExecuteMethodParams<"getTotalSupply">
    ): Promise<QISFundTypes.SignExecuteMethodResult<"getTotalSupply">> => {
      return signExecuteMethod(QISFund, this, "getTotalSupply", params);
    },
    updateNav: async (
      params: QISFundTypes.SignExecuteMethodParams<"updateNav">
    ): Promise<QISFundTypes.SignExecuteMethodResult<"updateNav">> => {
      return signExecuteMethod(QISFund, this, "updateNav", params);
    },
    buyShares: async (
      params: QISFundTypes.SignExecuteMethodParams<"buyShares">
    ): Promise<QISFundTypes.SignExecuteMethodResult<"buyShares">> => {
      return signExecuteMethod(QISFund, this, "buyShares", params);
    },
    sellShares: async (
      params: QISFundTypes.SignExecuteMethodParams<"sellShares">
    ): Promise<QISFundTypes.SignExecuteMethodResult<"sellShares">> => {
      return signExecuteMethod(QISFund, this, "sellShares", params);
    },
  };

  async multicall<Calls extends QISFundTypes.MultiCallParams>(
    calls: Calls
  ): Promise<QISFundTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends QISFundTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<QISFundTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends QISFundTypes.MultiCallParams | QISFundTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(QISFund, this, callss, getContractByCodeHash);
  }
}
